sudo: enabled
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

env:
  - COVERAGE=0.5

script:
  - ./gradlew clean jar
  - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check


  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/user check

after_success:
  - set -x -v;
    set  -e;
    if [ "${COVERAGE}" = 0.30 ]; then
        echo 'WIP'
    else
        echo 'Ignore'
    fi
