sudo: enabled
language: java
install: skip

jdk: oraclejdk8

os: linux
dist: trusty
jdk: oraclejdk8

env:
         - COVERAGE=0.5

install:
        - ./gradlew clean jar

script:
        - ./gradlew test

after_success:
        - ./gradlew jacocoTestReport
        - /usr/bin/find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
        - ./gradlew test jacocoTestCoverageVerification

deploy:
        provider: script
        script: echo 'WIP'
        on: 
                all_branches: true
