sudo: enabled
language: java

#os: linux
#dist: trusty
jdk: oraclejdk9

install:
        - ./gradlew clean jar

script:
        - ./gradlew test
        #  - echo 'testing coming soon'
        #- echo 'Using pull request rather than push from commandline!'
 
