sudo: enabled
language: java
install: skip

jdk: oraclejdk8

os: linux
dist: trusty
jdk: oraclejdk8

env:
        - COVERAGE=0.50

install:
        - ./gradlew clean jar

script:
        - ./gradlew test

after_success:
        - ./gradlew jacocoTestReport
        - /usr/bin/find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deplay:
        - COVERAGE=0.35./gradlew test jacocoTestCoverageVerification

deploy:
       - echo 'WIP'
