sudo: enabled
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

install:
        - ./gradlew clean jar

script:
        - ./gradlew test

after_success:
        - ./gradlew jacocoTestReport
        - /usr/bin/find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
        #  - echo 'testing coming soon'
        #- echo 'Using pull request rather than push from commandline!'
 
