sudo: enabled
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew clean jar
  - echo 'testing coming soon'
  - echo 'Using pull request rather than push from commandline"
