sudo: enabled
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

env:
        - COVERAGE=0.5

install:
        - ./gradlew clean jar

script:
        - ./gradlew test

after_success:
        - ./gradlew jacocoTestReport
        - /usr/bin/find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
        - ./gradlew test jacocoTestCoverageVerification

#Trying example from https://docs.travis-ci.com/user/deployment/script/
deploy:
        provider: script:
        script: echo 'WIP'
        on:
                tags: true
                all_branches: true
