sudo: enabled
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

env:
  - COVERAGE=0.5

script:
  - ./gradlew clean jar
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - /usr/bin/find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - COVERAGE=0.5 ./gradlew test jacocoTestCoverageVerification
    #  - echo 'testing coming soon'
    #- echo 'Using pull request rather than push from commandline!'

after_success:
  - set -x -v;
    set  -e;
    if [ "${COVERAGE}" = 0.5 ]; then
        echo 'WIP'
    else
        echo 'Ignore'
    fi
