sudo: enabled
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8


stages:
  - targets

jobs:
        include:
                - stage: targets
                  name: "UI JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "CART JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "USER JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "ORDER JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/order check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.25"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "REPO-CART JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "PRODUCT-USER JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "REPO-USER JDK8"
                  jdk: oraclejdk8
                  install: skip
                  script:
                        - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/user check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.25"]; then
                                echo 'WIP'
                       else
                       fi;


                - stage: targets
                  name: "UI JD9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "CART JDK9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "USER JDK9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "ORDER JDK9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/order check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.25"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "REPO-CART JDK9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "PRODUCT-USER JDk9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.5"]; then
                                echo 'WIP'
                       else
                       fi;

                - stage: targets
                  name: "REPO-USER JDK9"
                  jdk: oraclejdk9
                  install: skip
                  script:
                        - COVERAGE=0.25 ./gradlew -p ./monolithic/repository/user check
                  after_success:
                       set -x -v;
                       set -e;
                       if [ "${COVERAGE}" = "0.25"]; then
                                echo 'WIP'
                       else
                       fi;


